version: '3.8'

services:
  backend:
    image: trackit:1
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - target: 8080
        published: 9081
        protocol: tcp
        mode: host
    networks:
      - desarrollo_net  # Cambiado de trackit_net a desarrollo_net

  dbclases:
    image: mysql:8.4.0
    environment:
      - TZ=America/Guayaquil
      - MYSQL_DATABASE=trackit
      - MYSQL_ROOT_PASSWORD=3132003Aj933sebas@
      - MYSQLDATA=/var/lib/mysql/data/mysqldata
    volumes:
      - mysql_data:/var/lib/mysql/data/mysqldata
    networks:
      - desarrollo_net  # Cambiado de trackit_net a desarrollo_net

volumes:
  mysql_data:
    external: true

networks:
  desarrollo_net:
    external: true  # Asegúrate de que desarrollo_net esté definida como external
